// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHubU81GQJ5Esw2QQidsqxnq8iLdKeqS4',
    appId: '1:662252143939:web:46607ebbce2eaa0999dbf6',
    messagingSenderId: '662252143939',
    projectId: 'psychologicalcounseling-ecdee',
    authDomain: 'psychologicalcounseling-ecdee.firebaseapp.com',
    storageBucket: 'psychologicalcounseling-ecdee.firebasestorage.app',
    measurementId: 'G-GZ48WGSFPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yj8rOgzXEKJhdYxXGF9vRyp3YwhUwRA',
    appId: '1:662252143939:android:5c538586665bd0a699dbf6',
    messagingSenderId: '662252143939',
    projectId: 'psychologicalcounseling-ecdee',
    storageBucket: 'psychologicalcounseling-ecdee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7QYYEquwLRFAnNvhDUY5OkC9hf4mNmI',
    appId: '1:662252143939:ios:6a658c3aa80cd5ca99dbf6',
    messagingSenderId: '662252143939',
    projectId: 'psychologicalcounseling-ecdee',
    storageBucket: 'psychologicalcounseling-ecdee.firebasestorage.app',
    iosBundleId: 'com.example.a4iProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7QYYEquwLRFAnNvhDUY5OkC9hf4mNmI',
    appId: '1:662252143939:ios:6a658c3aa80cd5ca99dbf6',
    messagingSenderId: '662252143939',
    projectId: 'psychologicalcounseling-ecdee',
    storageBucket: 'psychologicalcounseling-ecdee.firebasestorage.app',
    iosBundleId: 'com.example.a4iProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHubU81GQJ5Esw2QQidsqxnq8iLdKeqS4',
    appId: '1:662252143939:web:cfc1d9a4eb74959699dbf6',
    messagingSenderId: '662252143939',
    projectId: 'psychologicalcounseling-ecdee',
    authDomain: 'psychologicalcounseling-ecdee.firebaseapp.com',
    storageBucket: 'psychologicalcounseling-ecdee.firebasestorage.app',
    measurementId: 'G-HQFJG34VD9',
  );

}